### PR TITLE
Bump Go to 1.15 and Go dependencies

### PR DESCRIPTION
**Pull request by tjanez**
Bump Oasis Core dependency to 20.11.1.

### CODE REVIEW

**Review by kostko — APPROVED** [review]

**Comment by ptrus** [comment]
should we also setup dependabot for dependencies?

**Comment by kostko** [comment]
Yeah, we should.

**Comment by tjanez** [comment]
Agreed.

@ptrus, would you set it up?

**Comment by ptrus** [comment]
yeah i can :-)

**Pull request merged**
